import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// Build a one-page GPSR "compliance passport" PDF for a product — a downloadable
// proof document a merchant can hand to a regulator or marketplace.
export async function buildPassportPdf({ product, record, rp, mf, shopDomain }) {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  let y = 792;
  const width = 595 - margin * 2;
  const ink = rgb(0.1, 0.1, 0.12);
  const grey = rgb(0.45, 0.45, 0.5);
  const accent = rgb(0.7, 0.23, 0);

  const text = (s, x, yy, f = font, size = 10, color = ink) =>
    page.drawText(String(s || ""), { x, y: yy, size, font: f, color });

  const wrap = (s, x, yy, size = 10, f = font, color = ink, lh = 14) => {
    const words = String(s || "").split(/\s+/);
    let line = "";
    let cursorY = yy;
    for (const w of words) {
      const test = line ? line + " " + w : w;
      if (f.widthOfTextAtSize(test, size) > width - (x - margin)) {
        text(line, x, cursorY, f, size, color);
        cursorY -= lh;
        line = w;
      } else line = test;
    }
    if (line) { text(line, x, cursorY, f, size, color); cursorY -= lh; }
    return cursorY;
  };

  // Header
  text("GPSR Product Safety Passport", margin, y, bold, 18);
  y -= 22;
  text("General Product Safety Regulation (EU) 2023/988 — Article 45 & 47", margin, y, font, 9, grey);
  y -= 12;
  text(`Issued ${new Date().toLocaleDateString()} · ${shopDomain}`, margin, y, font, 9, grey);
  y -= 16;
  page.drawLine({ start: { x: margin, y }, end: { x: 595 - margin, y }, thickness: 1, color: rgb(0.85, 0.85, 0.88) });
  y -= 26;

  // Product
  text("PRODUCT", margin, y, bold, 11, accent); y -= 16;
  text(product.title || "—", margin, y, bold, 13); y -= 20;

  const section = (title) => { text(title, margin, y, bold, 11, accent); y -= 16; };
  const field = (label, value) => {
    text(label, margin, y, bold, 9);
    y = wrap(value || "—", margin + 130, y, 10);
    y -= 4;
  };

  const idParts = [];
  if (record.gtin) idParts.push(`GTIN ${record.gtin}`);
  if (record.modelNumber) idParts.push(`Model ${record.modelNumber}`);
  if (record.batchNumber) idParts.push(`Batch ${record.batchNumber}`);
  if (record.serialNumber) idParts.push(`Serial ${record.serialNumber}`);

  section("IDENTIFIERS");
  field("Identifier", idParts.join("  ·  ") || "—");
  field("CE marking", record.ceMarked ? "Yes" : "No");
  y -= 6;

  section("EU RESPONSIBLE PERSON");
  if (rp) {
    field("Name", rp.legalName + (rp.companyName ? `, ${rp.companyName}` : ""));
    field("Address", `${rp.streetAddress}, ${rp.city} ${rp.postalCode}, ${rp.country}`);
    field("Contact", `${rp.email}  ·  ${rp.phone}`);
  } else { field("Name", "Not assigned"); }
  y -= 6;

  section("MANUFACTURER");
  if (mf) {
    field("Name", mf.legalName + (mf.tradeName ? ` (${mf.tradeName})` : ""));
    field("Address", `${mf.streetAddress}, ${mf.city} ${mf.postalCode}, ${mf.country}`);
  } else { field("Name", "Not assigned"); }
  y -= 6;

  section("SAFETY WARNINGS");
  const warnings = Array.isArray(record.warnings) ? record.warnings : [];
  if (warnings.length === 0) { field("Warnings", "None recorded"); }
  else {
    for (const w of warnings) {
      text(String(w.locale).toUpperCase(), margin, y, bold, 9);
      y = wrap(w.text, margin + 130, y, 10);
      y -= 4;
      if (y < 90) break;
    }
  }
  y -= 6;

  if (record.careInstructions) {
    section("CARE & USAGE");
    y = wrap(record.careInstructions, margin, y, 10);
  }

  // Footer
  page.drawLine({ start: { x: margin, y: 60 }, end: { x: 595 - margin, y: 60 }, thickness: 0.5, color: rgb(0.85, 0.85, 0.88) });
  text("Generated by GPSR Compliance Hub. This document summarises the safety information on file for the product above.", margin, 46, font, 7, grey);

  return await doc.save();
}
